[package]
name = "snake"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13.0", features = ["dynamic_linking", "wayland"] }
rand = "0.8.5"
serde = "1.0.197"
serde_json = "1.0.114"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
